name: AI News – daily build

on:
  schedule:
    # JST 08:50（= UTC 23:50）
    - cron: '50 23 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Build news JSON
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GEMINI_MODEL: ${{ vars.GEMINI_MODEL }}  # ここに 'gemini-2.5-pro' を設定して渡す
          X_BEARER_TOKEN: ${{ secrets.X_BEARER_TOKEN }}
        run: python scripts/build_news.py
      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add news/latest.json news/*.json || true
          git commit -m "chore: daily AI news JSON" || echo "nothing to commit"
          git push
